//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameSimulationN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityBuilding
    {
        public int Id { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> BuildingId { get; set; }
        public Nullable<int> Levels { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual City City { get; set; }
        public virtual BuildingType BuildingType { get; set; }
    }
}
